version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./project-management-system
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
